server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 256;

    location /elk-sizer/ {
        try_files $uri $uri/ /elk-sizer/index.html;
    }

    location /elk-sizer/assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
